# Generated by Django 6.0.2 on 2026-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_type',
            field=models.CharField(choices=[('BINGO', 'Bingo'), ('OXO', 'Tic-Tac-Toe')], default='BINGO', max_length=10),
        ),
    ]
